on:
  pull_request: 
    branches: [main]
  workflow_dispatch:  # Permite rodar manualmente

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout/Clone do projeto
        uses: actions/checkout@v4

      - name: Instalar dependências do projeto
        run: npm install

      - name: Rodar Testes
        uses: cypress-io/github-action@v6
        with: 
          record: true
      
      - name: Salvar relatório como artefato no Github Actions
        uses: actions/upload-artifact@v4
        with:
          name: relatorio-testes
          path: cypress/reports/html


 
